use_frameworks!

platform :ios, '9.0'

target 'TWSegmentView_Example' do
  pod 'TWSegmentView', :path => '../'

  target 'TWSegmentView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
