use_frameworks!

source 'https://github.com/tanwang11/TWSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '9.0'

target 'TWSegmentView_Example' do
  pod 'TWSegmentView', :path => '../'
  pod 'Masonry'
  pod 'TWUI'

  target 'TWSegmentView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
